/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarViewer: typeof import('./src/components/AvatarViewer/index.vue')['default']
    Backtop: typeof import('./src/components/Backtop/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    ComponentCard: typeof import('./src/components/ComponentCard/index.vue')['default']
    Confirm: typeof import('./src/components/Confirm/index.vue')['default']
    Contextmenu: typeof import('./src/components/ContextMenu/contextmenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary/index.vue')['default']
    ErrorComponent: typeof import('./src/components/ErrorComponent/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Leftbar: typeof import('./src/components/Layout/leftbar/leftbar.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Login: typeof import('./src/components/Login/login.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/MdEditor.vue')['default']
    Rightheader: typeof import('./src/components/Layout/rightheader/rightheader.vue')['default']
    Rightmain: typeof import('./src/components/Layout/rightmain/rightmain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./src/components/SkeletonCard/index.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle/index.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
